Script to get sample id of Input_all tensor and to find shap value of specific sample

In [1]:
import pandas as pd
import numpy as np

from datasets.dataset import FireDataset
from pathlib import Path
import json
config_path = Path("/Users/I566184/bachelorarbeit_coding/mesogeos/ml_tracks/a_fire_danger/configs/config_mlp/config_train.json")
csv = Path("/Users/I566184/bachelorarbeit_coding/mesogeos/csv/test_softmax_csv/test_softmax_outputs_lstm.csv")
with open(config_path, "r") as f:
    config = json.load(f)

In [2]:
test_dataset = FireDataset(
    dataset_root=Path("/Users/I566184/bachelorarbeit_coding/mesogeos/ml_tracks/a_fire_danger/a.danger_forecasting"),
    train_val_test='test',
    dynamic_features=config["features"]["dynamic"],
    static_features=config["features"]["static"]
)

Test Positives: 1369.0 / Test Negatives: 2738.0
Test Dataset length 4107.0


In [3]:
def get_sample (target_sample):
    row = df[df['sample_id']==target_sample]
    if row.empty:
        print(f"Sample {target_sample} not found.")
        return None

    sample_idx = row['index']
    print(f"Our original sample {target_sample} converts now to sample: {sample_idx}")
    return sample_idx

In [68]:
#Fire in Greece 
first_biggest_Fire_Test = get_sample(4792)

Our original sample 4792 converts now to sample: 479    479
Name: index, dtype: int64


In [67]:
#Fire in Spain
second_biggest_Fire_Test = get_sample(679)

Our original sample 679 converts now to sample: 3984    3984
Name: index, dtype: int64


In [66]:
#Fire in Algeria 
third_biggest_Fire_Test = get_sample(8418)

Our original sample 8418 converts now to sample: 3505    3505
Name: index, dtype: int64


In [8]:
#Fire in Spain 2.0 
fourth_biggest_Fire_Test = get_sample(1645)

Our original sample 1645 converts now to sample: 4091    4091
Name: index, dtype: int64


In [7]:
#Fire in Portugal 
fifth_biggest_Fire_Test = get_sample(1676)

Our original sample 1676 converts now to sample: 3594    3594
Name: index, dtype: int64


In [5]:
df = pd.read_csv(csv)
df['index'] = np.arange(len(df))

In [6]:
df[(df['sample_id']==4792) | (df['sample_id']==679) | (df['sample_id']==8418) | (df['sample_id']==1645) | (df['sample_id']==1676)]

prob        lat        lon  sample_id  label  log_burned_area  index
479   0.979855  23.334165  38.818407       4792      1        10.844374    479
3505  0.942400   4.172912  36.593164       8418      1        10.322230   3505
3594  0.932845  -7.497026  40.308615       1676      1        10.136977   3594
3984  0.490033  -6.037025  41.738409        679      1        10.389856   3984
4091  0.113981  -6.218267  41.899512       1645      1        10.241601   4091

In [55]:
get_sample(4792)

Our original sample 4792 converts now to sample: 479


479

In [56]:
df

prob        lat        lon  sample_id  label  log_burned_area  index
0     0.886618  -7.033854  40.983236        728      1         5.056246      0
1     0.002440  11.563537  43.399789      16438      0         3.401197      1
2     0.276308  -5.724887  34.649853      17300      0         3.401197      2
3     0.023041  34.802724  37.318130      15725      0         3.401197      3
4     0.007572  -4.526680  40.983236      15141      0         3.401197      4
...        ...        ...        ...        ...    ...              ...    ...
4102  0.000312  30.040100  38.425717      16004      0         3.401197   4102
4103  0.981715  19.356921  42.493582       6028      1         5.886104   4103
4104  0.028076  15.591126  41.708202      16621      0         3.401197   4104
4105  0.069568  10.516364  35.707095      17064      0         3.401197   4105
4106  0.056229   9.167122  40.157580      15822      0         3.401197   4106

[4107 rows x 7 columns]

In [59]:
pos = df[df['label'] ==1]
pos

prob        lat        lon  sample_id  label  log_burned_area  index
0     0.886618  -7.033854  40.983236        728      1         5.056246      0
8     0.605983   8.341466  35.183508       8372      1         5.476463      8
12    0.980295  12.953055  41.587374       3685      1         3.988984     12
30    0.971927  17.151817  40.590546       3013      1         3.610918     30
38    0.978868   8.301190  36.693854       8509      1         5.356586     38
...        ...        ...        ...        ...    ...              ...    ...
4091  0.113981  -6.218267  41.899512       1645      1        10.241601   4091
4097  0.979037  -6.892888  42.423099       1612      1         5.267858   4097
4100  0.864642   8.925467  35.113025       8348      1         4.406719   4100
4101  0.996553  -5.583922  35.304336       8466      1         9.032290   4101
4103  0.981715  19.356921  42.493582       6028      1         5.886104   4103

[1369 rows x 7 columns]

In [60]:
neg = df[df['label'] ==0]
neg

prob        lat        lon  sample_id  label  log_burned_area  index
1     0.002440  11.563537  43.399789      16438      0         3.401197      1
2     0.276308  -5.724887  34.649853      17300      0         3.401197      2
3     0.023041  34.802724  37.318130      15725      0         3.401197      3
4     0.007572  -4.526680  40.983236      15141      0         3.401197      4
5     0.490169  -3.207644  40.610684      16716      0         3.401197      5
...        ...        ...        ...        ...    ...              ...    ...
4099  0.391554  -3.358679  38.284751      15434      0         3.401197   4099
4102  0.000312  30.040100  38.425717      16004      0         3.401197   4102
4104  0.028076  15.591126  41.708202      16621      0         3.401197   4104
4105  0.069568  10.516364  35.707095      17064      0         3.401197   4105
4106  0.056229   9.167122  40.157580      15822      0         3.401197   4106

[2738 rows x 7 columns]

In [4]:
samples = np.load("/Users/I566184/bachelorarbeit_coding/mesogeos/csv/shap_values_0517_175347_mlp_samples.npy")
labels = np.load("/Users/I566184/bachelorarbeit_coding/mesogeos/csv/shap_values_0517_175347_mlp_labels.npy")
combined = pd.read_csv("/Users/I566184/bachelorarbeit_coding/mesogeos/csv/shap_values/shap_values_0517_175347_mlp_combined.csv")

print(f"Samples shape: {samples.shape}")
print(f"Labels shape: {labels.shape}")

Samples shape: (4107,)
Labels shape: (4107,)


In [32]:
def get_label_for_sample(sample_id):
    """
    Gibt das zugehörige Label für ein gegebenes Sample-ID zurück.
    
    sample_id: int – die Sample-ID, nach der gesucht werden soll
    """
    # Überprüfen, ob sample_id in samples vorhanden ist
    matches = np.where(samples == sample_id)
    print(f"matches size {matches}")

    if len(matches) == 0:
        print(f"Sample ID {sample_id} wurde nicht gefunden.")
        return None

    index = matches[0]  # ersten passenden Index nehmen
    label = labels[index]

    print(f"Sample ID: {sample_id}")
    print(f"Index im Array: {index}")
    print(f"Label: {label}")
    print(f"Our original sample {sample_id} converts now to sample: {index}")

    return label

In [33]:
get_label_for_sample(4792)

matches size (array([1883]),)
Sample ID: 4792
Index im Array: [1883]
Label: [1]
Our original sample 4792 converts now to sample: [1883]


array([1])

In [23]:
get_label_for_sample(679)

Sample ID: 679
Index im Array: [139]
Label: [1]


array([1])

In [24]:
get_label_for_sample(8418)

Sample ID: 8418
Index im Array: [413]
Label: [1]


array([1])

In [25]:
get_label_for_sample(1645)

Sample ID: 1645
Index im Array: [3367]
Label: [1]


array([1])

In [6]:
combined[(combined['sample_id']==4792) | (combined['sample_id']==679) | (combined['sample_id']==8418) | (combined['sample_id']==1645) | (combined['sample_id']==1676)]


sample_id  label          x          y  shap_class_0_d2m_t-30  \
139         679      1  -6.037025  41.738409               0.000000   
413        8418      1   4.172912  36.593164               0.000000   
1883       4792      1  23.334165  38.818407              -0.008156   
3367       1645      1  -6.218267  41.899512               0.002684   
3569       1676      1  -7.497026  40.308615               0.004278   

      shap_class_0_lai_t-30  shap_class_0_lst_day_t-30  \
139                0.000000                   0.000000   
413                0.000000                   0.000000   
1883               0.000000                  -0.011522   
3367              -0.006224                   0.000000   
3569              -0.007987                   0.000000   

      shap_class_0_lst_night_t-30  shap_class_0_ndvi_t-30  \
139                      0.000000                0.001708   
413                      0.000422               -0.017579   
1883                     0.000000               -0.014563   
3367                     0.000000                0.000000   
3569                     0.000000                0.000978   

      shap_class_0_rh_t-30  ...  shap_class_1_slope_t-1  \
139               0.000000  ...               -0.001545   
413               0.007909  ...                0.000000   
1883              0.000000  ...                0.000000   
3367              0.000000  ...                0.000000   
3569              0.008888  ...                0.000000   

      shap_class_1_lc_agriculture_t-1  shap_class_1_lc_forest_t-1  \
139                          0.000000                         0.0   
413                          0.000000                         0.0   
1883                         0.000000                         0.0   
3367                         0.001223                         0.0   
3569                        -0.008790                         0.0   

      shap_class_1_lc_grassland_t-1  shap_class_1_lc_settlement_t-1  \
139                        0.000000                             0.0   
413                        0.000000                             0.0   
1883                       0.002167                             0.0   
3367                       0.000000                             0.0   
3569                       0.000000                             0.0   

      shap_class_1_lc_shrubland_t-1  shap_class_1_lc_sparse_vegetation_t-1  \
139                             0.0                               0.012161   
413                             0.0                               0.000000   
1883                            0.0                               0.000000   
3367                            0.0                               0.001534   
3569                            0.0                               0.000000   

      shap_class_1_lc_water_bodies_t-1  shap_class_1_lc_wetland_t-1  \
139                                0.0                     0.000000   
413                                0.0                     0.000000   
1883                               0.0                    -0.000439   
3367                               0.0                     0.000000   
3569                               0.0                     0.000000   

      shap_class_1_population_t-1  
139                      0.000000  
413                      0.000000  
1883                     0.000000  
3367                     0.000000  
3569                     0.002859  

[5 rows x 1444 columns]